contact_links:
  - name: Anubhav Gain
    url: https://www.linkedin.com/in/anubhavgain/
    about: A DevSecOps Engineer.
  - name: Hriday Sheth
    url: https://www.linkedin.com/in/hridaysheth/
    about: Official maintainer of this Ai based Chat Bot.
